name: faxmachine
favicon: null
layout_spectrum: 0.4396608551032841
typography_spectrum: 0.7614118272904307
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.15400524344295263
  lightness: 0.10262223985046148
  saturation: 0.1333559777121991
  rhythmicContrast: 0.6702616009861231
purpose: []
